version: '3.8'

services:
  coordinator:
    image: citusdata/citus:latest
    container_name: coordinator
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - citus_network

  worker1:
    image: citusdata/citus:latest
    container_name: worker1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - citus_network

  worker2:
    image: citusdata/citus:latest
    container_name: worker2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - citus_network

  manager:
    image: citusdata/membership-manager:latest
    container_name: manager
    depends_on:
      - coordinator
      - worker1
      - worker2
    networks:
      - citus_network

networks:
  citus_network:
